#
# Copyright 2025 AISL Sejong University, Korea 
#	Licence  TBD
#

services:
  metacom2025-sejong:
    build: 
      context: .
      args: 
        USE_ENV: ${USE_ENV}
    image: metasejong-2025:release
    runtime: nvidia
    environment:
      - USE-ENV=${USE_ENV}
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - AMENT_PREFIX_PATH=/isaac-sim/exts/omni.isaac.ros2_bridge/humble
      - LD_LIBRARY_PATH=/isaac-sim/exts/omni.isaac.ros2_bridge/humble/lib:$LD_LIBRARY_PATH
      - PYTHONPATH=/isaac-sim/kit/python/lib/python3.10/site-packages:/isaac-sim/exts
      - USD_PLUGIN_PATH=/isaac-sim/exts/omni.usd.schema.isaac/plugins
      - ROS_DISTRO=humble
      - EXTENSIONS=omni.isaac.ros2_bridge
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - ${XAUTHORITY}:/root/.Xauthority:rw
      - ./workspace/cache/kit:/isaac-sim/kit/cache:rw
      - ./workspace/cache/ov:/root/.cache/ov:rw
      - ./workspace/cache/pip:/root/.cache/pip:rw
      - ./workspace/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - ./workspace/cache/computecache:/root/.nv/ComputeCache:rw
      - ./workspace/logs:/root/.nvidia-omniverse/logs:rw
      - ./workspace/data:/root/.local/share/ov/data:rw
      - ./workspace/documents:/root/Documents:rw
      - ./resources/models/meta-sejong:/root/Documents/meta-sejong:rw
      - ./resources/models/robot:/root/Documents/robot:rw
      - ./resources/extensions/aisl-robot-pickandplace:/root/Documents/Kit/shared/exts/aisl.omnigraph.extension:rw
      - ./resources/extensions/omni.isaac.sim.base.kit:/isaac-sim/apps/omni.isaac.sim.base.kit:rw
    network_mode: "host"
    entrypoint: ["/isaac-sim/python.sh", "/simulation_app/run_simulation_app.py"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
