version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  languages: ["ko", "en"]

python:
  install:
    - requirements: guide/requirements.txt

# 다국어 지원 설정
locales:
  - ko
  - en

# 기본 언어 설정
default_locale: ko 
