version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - pip install sphinx-intl
      - sphinx-intl update -p _build/gettext -l ko

sphinx:
  configuration: guide/docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: guide/requirements.txt

# Build documentation in all languages
formats:
  - htmlzip
  - pdf

# 다국어 지원 설정
locales:
  - ko
  - en

# 기본 언어 설정
default_locale: en 
